[package]
name = "xluck"
version = "0.0.1"
published-at = "0x165f01c1cd0e30b65b43f14f86b947ce28e61cb37b04f2cedffbb806e222d3de"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
token = { local = "../token" }

[addresses]
xluck = "0x165f01c1cd0e30b65b43f14f86b947ce28e61cb37b04f2cedffbb806e222d3de"
